version: '3'
services:
  #PHP App
  app:
    build:
      context: .
      dockerfile: config/dockerfile
    image: christexe/php:8.2.8-fpm-bullseye
    container_name: '${serverName}_App'
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      BD_NAME : "${BD_dbname}"
      BD_PASSWORD : "${BD_password}"
      BD_SERVER : "${BD_servername}"
      BD_USER : "${BD_username}"
    working_dir: /var/www/html
    volumes:
      - ${pathApp}:/var/www/html/
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./config/www.conf:/usr/local/etc/www.conf

  #Nginx Service
  nginx:
    image: nginx:1.24
    container_name: '${serverName}_server'
    restart: unless-stopped
    tty: true
    ports:
      - ${port}:80
    volumes:
      - ${pathApp}:/var/www/html/
      - ./config/conf.d/:/etc/nginx/conf.d/
  sql-server-db:
    container_name: '${serverName}_DB'
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${BD_password}"
      ACCEPT_EULA: "Y"
  # mysql:
  #   container_name: DB_${serverName}
  #   image: mysql:8.1
  #   command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "${passwordDBSQL}*"
  #     MYSQL_DATABASE: ${databaseName}
  #     MYSQL_USER: ${username}
  #     MYSQL_PASSWORD: ${password}
